### ISSUE TITLE
How to set Lanscape page!

### ISSUE THREAD

**Issue by gunvesxco** [kempsteven/vue-html2pdf#1]
I think for the props for lanscape page is not set yet.

**Comment by kempsteven** [comment]
yes, I have not set the props for landscape page yet, will be adding that in the next update

**Comment by gunvesxco** [comment]
Hi...

Vue-html2pdf is very powerfull and easy to implement. But i have a
questions, do you have any idea for set lanscape page in vue html2pdf.

Thank you and best regards.

**Comment by kempsteven** [comment]
Hello,

Sorry, but currently in vue-html2pdf, I have not implemented a way for a user to set the pdf orientation, it is only set as a portrait orientation.

since next update will take a bit, and this package is wrapper of html2pdf.js, I highly recommend you using this package for better control of the pdf's settings [html2pdf.js](https://github.com/eKoopmans/html2pdf.js/blob/master/README.md) for a quick solution.

To get you started, this is a sample code for the html2pdf.js, in vue:
```
// to install
// npm install --save html2pdf.js

<template>
     <section ref="pdfContent>
             // pdf content here
     </section>
</template>

import html2pdf from 'html2pdf.js'
export default {
     methods: {
           async generatePdf () {
                  const element = this.$refs.pdfContent

                  const opt = {
				margin: 0,

				filename: `name.pdf`,

				image: {
					type: 'jpeg', 
					quality: 0.98
				},

				html2canvas: {
					scale: 2
				},

				jsPDF: {
					unit: 'in',
					format: 'a4',
                                        // Here is where you set your pdf orientation (portrait, landscape)
					orientation: 'landscape'
				}
		   }

                   // Download PDF
	          await html2pdf().set(opt).from(element).save()
           }
     }
}
```

**Comment by gunvesxco** [comment]
Thanks for your answer.
I will try use html2pdf.js

Thanks a lot. Are you have whatsapp number. Maybe we can get in touch after
this.

Best regards,
Eko Nursahid

**Comment by kempsteven** [comment]
Thanks for appreciating vue-html2pdf! if you'd like you can give a link to your LinkedIn, i could add you

**Comment by gunvesxco** [comment]
You're welcome... This my linkedin profile.

https://www.linkedin.com/in/eko-nursahid-1253b89a

**Comment by kempsteven** [comment]
Hi, the new feature has been implemented, I thought it would take a while lol.

you can now use props called:
```
   ...
   pdf-orientation="landscape" // used to set the pdf's orientation
   pdf-content-width="800px" // used to set the pdf's content width
   ...
```
you also see [documentation](https://github.com/kempsteven/vue-html2pdf/blob/master/README.md) for a more detailed explanation.
