### ISSUE TITLE
Image with base64 support

### ISSUE THREAD

**Issue by adronitis** [kempsteven/vue-html2pdf#10]
I need to load image into the PDF from the API link, however since it doesn't support remote link, can we add support to base64 image?

**Comment by silo** [comment]
Hi. 
I am writing, because i maybe have a related issue. I converted my images to base64 and storing them in the localstorage. But it doesn't work half of the times when i generate the PDF. 
@adronitis how did you solve this?

**Comment by adronitis** [comment]
Apparently the base64 didn't work for me (although over at html2pdf.js people say it worked for them), if you take a look at my fork: https://github.com/adronitis/vue-html2pdf/commit/4053e8a25349f5592e6f91b74ee31c3711884d5c 

I simply added an additional settings to html2canvas so I can link remote images.
 

> html2canvas: {
					scale: this.pdfQuality						
         			useCORS: true
				},		

> 

Hope this helps!

**Comment by kempsteven** [comment]
Thanks for the answer above I saw another issue of this package which lacks control on configuring the options of html2pdf.js, I will implement a way so the user could adjust all configs on html2pdf.js soon

As for now you have to wait for the image to render on the image tag before generating the PDF, so make sure to not generate the pdf while converting the image to a base64 and assigning it to the img src.

Sample of detecting if the image has loaded is this: https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_img_onload

**Comment by kempsteven** [comment]
You can now configure all options of html2pdf.js, using the props `html-to-pdf-options`

More details about the props here:
https://www.npmjs.com/package/vue-html2pdf#html-to-pdf-options
