### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by dhamdani666** [kempsteven/vue-html2pdf#108]
Hi , I installed vue-html2pdf with npm i vue-html2pdf with a Vue 3 but it does not seem to be compatible. 
When I try to import import VueHtml2pdf from 'vue-html2pdf' you get an error TypeError: selfHook.bind is not a function

Any suggestions?
Thank you.

**Comment by JohnniePeixoto** [comment]
Same here, i've found this package may it helps you too
https://github.com/sango-tech/vue3-simple-html2pdf

**Comment by kempsteven** [comment]
Hi currently Vue 3 is not yet supported, work for that is still pending due to a busy schedule,
I'll be working on that after things settle down, thanks for trying this package! :)
