### ISSUE TITLE
Access to more html2pdf.js options

### ISSUE THREAD

**Issue by rubenreyes2000** [kempsteven/vue-html2pdf#11]
Great package, we love it. I have a question - is there a way to pass other html2pdf.js options? We would like to tweak the generated PDF in ways that your options don't seem to allow. For example (see https://www.npmjs.com/package/html2pdf.js/v/0.9.0#options):

- Select image type (JPG, PNG)
- Control JPG image quality
- Set a scale factor (part of the html2canvas options: http://html2canvas.hertzen.com/configuration/)

Thank you!

**Comment by kempsteven** [comment]
Hey thanks, I do think its a good idea making those options available, will be doing that!

The only options available for now is these props:
pdf-quality = html2canvas.scale
pdf-format = jsPDF.format
pdf-orientation = jsPDF.orientation

**Comment by kempsteven** [comment]
You can now have access to the html2pdf.js options by using the prop `html-to-pdf-options` in version 1.4.0

Details of the props can be seen here:
https://www.npmjs.com/package/vue-html2pdf#html-to-pdf-options

**Comment by rubenreyes2000** [comment]
Sweet! Thank you!
