### ISSUE TITLE
移动端不支持Blob的pdf下载，怎么办？

### ISSUE THREAD

**Issue by weblove26** [kempsteven/vue-html2pdf#13]
移动端不支持Blob的pdf下载，怎么办？

**Comment by kempsteven** [comment]
Hi there, can you provide a sample of your code and if you have any, a sample of your error messages? so we can investigate what's happening.

I am sure this works on Chrome for android though

**Comment by kempsteven** [comment]
Feel free to open this issue again, if you still have questions.
Also if possible please use English, I had to google translate that haha
