### ISSUE TITLE
text display is shifting/moving down after generated

### ISSUE THREAD

**Issue by phojie** [kempsteven/vue-html2pdf#130]
**Describe the bug**
text display is shifting/moving down after generated

**Screenshots**
![Screen Shot 2022-03-16 at 7 13 30 PM](https://user-images.githubusercontent.com/33350692/158577663-49f8659f-973d-4e6c-abf9-64f224f44376.png)

**Package Version**
1.8.0

**Comment by cuongpv219** [comment]
I also had this problem, how did you fix it?

> **Describe the bug** text display is shifting/moving down after generated
> 
> **Screenshots** ![Screen Shot 2022-03-16 at 7 13 30 PM](https://user-images.githubusercontent.com/33350692/158577663-49f8659f-973d-4e6c-abf9-64f224f44376.png)
> 
> **Package Version** 1.8.0

**Comment by soumyabishi** [comment]
@phojie  Hey how did you fix it?

**Comment by phojie** [comment]
> [@phojie](https://github.com/phojie) Hey how did you fix it?

Yes, but I’ve already forgotten how I fixed it 😂
