### ISSUE TITLE
Use html2pdf__page-break only if necessary

### ISSUE THREAD

**Issue by JacquesJahnichen** [kempsteven/vue-html2pdf#140]
First of all thanks for this plugin.

How can I add a break (html2pdf__page-break for example) only if an element is cut ? The size of my document is variable. Exemple : 

![image](https://user-images.githubusercontent.com/16701017/181241332-078fad9a-8580-483a-90cf-7cd7c5ea7125.png)

**Comment by JacquesViviarto** [comment]
A little reminder on this subject

**Comment by JacquesViviarto** [comment]
If anyone has an idea to solve this problem, I welcome it.

**Comment by JacquesJahnichen** [comment]
One way to solve this is to use section

```
  <section class="pdf-item">
    <OrderDiscount />
  </section>
  <section class="pdf-item">
    <OrderConditionPrice />
  </section>
```
```
.pdf-item {
  page-break-inside: avoid;
}
```

You can also find options in : https://ekoopmans.github.io/html2pdf.js/#page-breaks
