### ISSUE TITLE
Use @beforeDownload and generatePdf() action generates two PDF

### ISSUE THREAD

**Issue by JacquesJahnichen** [kempsteven/vue-html2pdf#141]
Hello,

How can I add a button to "Dowload the PDF" and use @beforeDownload in a same time to add a footer ? When I do that I download two pdf

![image](https://user-images.githubusercontent.com/16701017/181247056-57ab633f-9572-4dfa-87d2-d474e4ba5630.png)

![image](https://user-images.githubusercontent.com/16701017/181246317-9ef7e63e-8baf-41a7-bbfb-478dcb48c941.png)

**Comment by JacquesViviarto** [comment]
A little reminder on this subject

**Comment by JacquesViviarto** [comment]
If anyone has an idea to solve this problem, it is welcome.

**Comment by rogerio-pereira** [comment]
+1

**Comment by rogerio-pereira** [comment]
@JacquesViviarto set both variables: preview-modal and enable-download to false

That solved for me

**Comment by AloneInMyMind** [comment]
> @JacquesViviarto set both variables: preview-modal and enable-download to false
> 
> That solved for me

The problem of this solution is that now the @hasDownloaded doesn't work anymore, if anyone has a solution please let me know

**Comment by rogerio-pereira** [comment]
@AloneInMyMind 
use beforeDownload, also set both variables.
It`s working for me

**Comment by JacquesViviarto** [comment]
Thanks for your help. This config work for me 

```
<vue-html2pdf
          :preview-modal="false" 
          :enable-download="false"
          @beforeDownload="beforeDownload">
```
