### ISSUE TITLE
Adding margin to options cut text in half

### ISSUE THREAD

**Issue by adronitis** [kempsteven/vue-html2pdf#15]
After adding margin (say 10 on 4 side) to options, sometimes text get cut off. I tried using the .pdf-item but doesn't seems to be working. Whats the best way to resolve this? 

![WhatsApp Image 2020-07-06 at 12 44 06](https://user-images.githubusercontent.com/1169705/86783136-37931180-c060-11ea-8992-5d85c65c6639.jpeg)

**Comment by adronitis** [comment]
Ok, it looks like if I add:

`pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }`

This would make the .pdf-item breaks properly when using margin. I suggest maybe is also good to add this as an option.

**Comment by kempsteven** [comment]
Hmm, I believe you can add that on html-to-pdf-options, ill have to test it first before adding it to documentation though.

I also recommend that you set the margin to 0 on the options for the script to work better. just add the margin on your .pdf-item elements, I still haven't added the margin option to the calculation of pagination, will take note of that.
