### ISSUE TITLE
The text movedown 

### ISSUE THREAD

**Issue by ChamkhiAnas** [kempsteven/vue-html2pdf#168]
The text and the html elements move out when i preview or download the pdf 

The HTML+CSS page before converting it to pdf  : 

<img width="930" alt="image" src="https://user-images.githubusercontent.com/59390833/212956260-6f670122-09c0-4a5b-949e-f805ef012f71.png">

The HTML+CSS page after converting it to pdf  : 
<img width="610" alt="poorquality" src="https://user-images.githubusercontent.com/59390833/212956340-b94e973d-e4f2-41af-9aa1-3aa12f526ecb.png">

Any solution or tips ? 

! ps : im using tailwind css

**Comment by ChamkhiAnas** [comment]
i found a quick solution for this problem 

wrap every text with a span with position: relative; top: -/*half of the size of the font*/

**Comment by IsTheJack** [comment]
This is not a solution for that actually. It's more a workaround. I'm facing it as well. I would reopen that because it's a very basic issue that this lib should prevent of

**Comment by itthikorn2542** [comment]
> i found a quick solution for this problem
> 
> wrap every text with a span with position: relative; top: -/_half of the size of the font_/
This work for me
