### ISSUE TITLE
styles not working

### ISSUE THREAD

**Issue by vana-dev** [kempsteven/vue-html2pdf#17]
No idea why, on preview-modal looks fine, but after generating I get plain text pdf :/ Also it doesn't work only on web server, when I run project on localhost, styles works.

**Comment by kempsteven** [comment]
Hmm where did you deploy your project? I deployed the [demo app](https://vue-html2pdf-demo.netlify.app/) for this package in Netlify and it works perfectly.
Please give me more context so we could try and debug it

**Comment by vana-dev** [comment]
Project is running in custom web server, I can't share, source code. It runs on newest version on nuxt.js 2.13.3 and node v10.14.2 component config:

`    <vue-html2pdf
      ref="html2Pdf"
      :show-layout="false"
      :enable-download="true"
      :preview-modal="false"
      :paginate-elements-by-height="1200"
      filename="products"
      :pdf-quality="2"
      pdf-format="a4"
      pdf-orientation="portrait"
      pdf-content-width="800px"
      @progress="onProgress($event)"
    >
      <WizardListPdf slot="pdf-content" :data="modalData" :list="myList" :category="currentCategory" :hotspots="currentHotspots" :all="printAll" />
    </vue-html2pdf>`

no errors in console

**Comment by vana-dev** [comment]
Ok, I figured it out. I had already installed jspdf module, so I removed it, and reinstall vue-html2pdf. Now everything works fine.

**Comment by kempsteven** [comment]
Okay cool
