### ISSUE TITLE
Does the generated pdf contain html elements?

### ISSUE THREAD

**Issue by 1591582901** [kempsteven/vue-html2pdf#18]
Hello, the pdf I am generating is a pure picture, can I generate text or pdf with hyperlinks?

**Comment by kempsteven** [comment]
It seems you have resolve your issue, but for future reference of other users you can generate pdf with hyperlinks by setting the `enableLinks` to `true` on `html-to-pdf-options` props.

**Here is a sample:**

```
htmlToPdfOptions: {
    margin: 0,
 
    filename: `hehehe.pdf`,
 
    image: {
        type: 'jpeg', 
        quality: 0.98
    },
 
    enableLinks: true,
 
    html2canvas: {
        scale: 1,
        useCORS: true
    },
 
    jsPDF: {
        unit: 'in',
        format: 'a4',
        orientation: 'portrait'
    }
}
```
Documentation for [html-to-pdf-options props](https://www.npmjs.com/package/vue-html2pdf#html-to-pdf-options)

**Comment by 1591582901** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kemp Steven"<notifications@github.com&gt;; 
发送时间: 2020年7月17日(星期五) 晚上8:47
收件人: "kempsteven/vue-html2pdf"<vue-html2pdf@noreply.github.com&gt;; 
抄送: "心若向阳，何惧忧伤。"<1591582901@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [kempsteven/vue-html2pdf] Does the generated pdf contain html elements? (#18)





 
It seems you have resolve your issue, but for future reference of other users you can generate pdf with hyperlinks by setting the enableLinks to true on html-to-pdf-options props.
 
Here is a sample:
 htmlToPdfOptions: {     margin: 0,       filename: `hehehe.pdf`,       image: {         type: 'jpeg',          quality: 0.98     },       enableLinks: true,       html2canvas: {         scale: 1,         useCORS: true     },       jsPDF: {         unit: 'in',         format: 'a4',         orientation: 'portrait'     } }  
Documentation for html-to-pdf-options props
