### ISSUE TITLE
App is crashed when there is more HTML

### ISSUE THREAD

**Issue by PhuHoaframgia** [kempsteven/vue-html2pdf#2]
Please try with more html data

**Comment by kempsteven** [comment]
Hi PhuHoaframgia, can you provide me a sample of more html data so i could debug the problem thanks!

**Comment by runkids** [comment]
I have same problem.
Please check [this loop.](https://github.com/kempsteven/vue-html2pdf/blob/7da86921de18f52f313c5778945b9878b7d196f4/src/vue-html2pdf.vue#L136) it will become infinity loop.

I try to modify this line 
`
for (const childElement of ArrOfContentChildren) {
`
then it's work.

**Comment by kempsteven** [comment]
sure ill look at that, but can I atleast get a sample of this more HTML data so that I could test the solution?

**Comment by kempsteven** [comment]
soo for @runkids comment, the for of loop should work perfectly on an HTMLCollection the (parentElement.children), but to be sure that there wont be any issues, I used the variable ArrOfContentChildren and change the spread operator to Array.from to convert the HTMLCollection to a normal array.

I will be closing this now, but if you ran again to a bug dont hesitate to open an issue again, but please provide a sample, and if there is any, a screenshot of the error on the console, Thanks!

ive publish the changes and it is now available on npm

**Comment by runkids** [comment]
Ok, thank you very much!
