### ISSUE TITLE
Image is blocked by CORS

### ISSUE THREAD

**Issue by nongtiny** [kempsteven/vue-html2pdf#20]
I fetch an image from CDN, and I already set useCors: true, but it's still got blocked.

**Comment by kempsteven** [comment]
hmm do you have any cors error on the console?
can I have a sample image URL from that cdn?

**Comment by kempsteven** [comment]
Feel free to open this, if the issue persist!

**Comment by missingeverytime** [comment]
Hi @kempsteven ,
This issue still happened when I add an image to a pdf.
Here is the code.
```html
<vue-html2pdf
        :show-layout="true"
        :float-layout="false"
        :enable-download="false"
        :preview-modal="true"
        :paginate-elements-by-height="1400"
        filename="hee hee"
        :pdf-quality="2"
        :manual-pagination="false"
        pdf-format="a4"
        pdf-orientation="landscape"
        :pdf-content-width="800"
        :html-to-pdf-options="htmlToPdfOptions"
        ref="html2Pdf">
        <section slot="pdf-content">
            <!-- PDF Content Here -->
      <img
          class="user-image"
          src="https://tikupic.21cnjy.com/2b/8e/2b8e0f8dc3583052c96be88209fe094c.png"
          alt="User Image"
          ref="userImage"
        />
        </section>
    </vue-html2pdf>
```
```javascript
computed: {
    htmlToPdfOptions() {
      return {
        html2canvas: {
          taintTest: true,
          useCORS: true
        }
      }
    }
  }
```
This image displays well on my website, 
<img width="587" alt="image" src="https://user-images.githubusercontent.com/16895572/102869798-20fa3e80-4477-11eb-9aa3-ea1d44e9f661.png">
but does not work well when I try to export PDF.
Here is the error message.
<img width="1031" alt="error-msg" src="https://user-images.githubusercontent.com/16895572/102869841-2a83a680-4477-11eb-82fb-752064d222fb.png">

So, would you help me to check this issue? In my opinion, this issue still belongs to CORS.
THX

**Comment by PujeBN** [comment]
how are you did you fix this error?
