### ISSUE TITLE
Can't load image

### ISSUE THREAD

**Issue by sid3r** [kempsteven/vue-html2pdf#23]
I'm using vue-cli to serve an app on localhost:8888, the image shows when inside a normal component, no cors issues, but the same code doesn't work with vue-html2pdf.

```
<section slot="pdf-content">
    <img src="/svg/logo.svg" alt="logo" height="90px">
</section>
```
```
:html-to-pdf-options="{
     html2canvas: { useCORS: true}
} 
```  

Why doesn't it work? anyone can provide a working example on how to load images.

**Comment by kempsteven** [comment]
Hmmm that doesn't look like a remote image, **is the image in your local files**?

So my assumption for now is the image path on the src might be wrong.

Enabling the config `html2canvas: { useCORS: true}` is for images that is from a remote server/link.
Have you tried enabling the prop `show-layout` to true to see your layout and if the image loaded?

For a working sample you could see me demo project for this package on the links below:
[Source Code](https://github.com/kempsteven/vue-html2pdf-demo)
[Live Demo](https://vue-html2pdf-demo.netlify.app/)

You could fork or clone it and play with it, there is a sample there on loading images

**Comment by sid3r** [comment]
@kempsteven I actually tried the same code in the vue template and it's working, so I guess that's fine there's no issue with the the image path. 

The same code doesn't work for the pdf, I just added the _useCors: true_ to see if it changes anything, but no it's has no effect cause it's useless here as you mentioned. So where's the issue exactly? I expected local files to work out of the box ... 

Even an absolute path _http://localhost:8888/svg/logo.svg_ doesn't work by the way :/

**Comment by kempsteven** [comment]
Ohh okay cool, thanks for telling I wasn't aware we can't load .svg images

**Comment by sid3r** [comment]
You're welcome, now you can implement that too. Actually it took me some time to resolve the issue since I supposed that svg is supported out of the box.

**Comment by bhushan** [comment]
why .svg is not supported then ?? @kempsteven

**Comment by kempsteven** [comment]
Hey @bhushan, this is an issue with html2pdf.js
as mentioned by the creator [here](https://github.com/eKoopmans/html2pdf.js/issues/185#issuecomment-455869320)

You could try and do this using the [html-to-pdf-options](https://github.com/kempsteven/vue-html2pdf#html-to-pdf-options) props:
sample:
```
:html-to-pdf-options="{
     // Other options here
     html2canvas: {
       // Other options here
        onclone: (element) => {
            const svgElements = Array.from(element.querySelectorAll('svg'));
            svgElements.forEach(s => {
                const bBox = s.getBBox();
                s.setAttribute("x", bBox.x);
                s.setAttribute("y", bBox.y);
                s.setAttribute("width", bBox.width);
                s.setAttribute("height", bBox.height);
          }
     }
}"
```
