### ISSUE TITLE
When we click on close button from modal it popups again and again.. 

### ISSUE THREAD

**Issue by bhushan** [kempsteven/vue-html2pdf#25]
```js
download () {
 this.$refs.html2Pdf.generatePdf()
}
```

using this method with example template you given .. 

```html
<template>
   <div>
     <vue-html2pdf
        :show-layout="false"
        :enable-download="true"
        :preview-modal="true"
        :paginate-elements-by-height="1400"
        filename="hee hee"
        :pdf-quality="2"
        :manual-pagination="false"
        pdf-format="a4"
        pdf-orientation="landscape"
        pdf-content-width="800px"

        @progress="onProgress($event)"
        @hasStartedGeneration="hasStartedGeneration()"
        @hasGenerated="hasGenerated($event)"
        ref="html2Pdf"
    >
        <section slot="pdf-content">
            <h1>hello</h1>
        </section>
    </vue-html2pdf>
   </div>
</template>
```

**Comment by kempsteven** [comment]
Have you tried adding console.log on the download method of yours to see if you are only triggering the method once?

Also if you don't need the preview modal, you could set the props `:preview-modal="false"`

**Comment by bhushan** [comment]
preview-modal is fantastic option i want to use it.


and when i click close button from modal .. it triggers preview modal again.. i was debugging this this is something related to has already parsed and progress..

**Comment by bhushan** [comment]
I noticed progress goes to zero and then again it starts parsing.. i am checking it .. will ping you here if i found anything..

**Comment by kempsteven** [comment]
Hmm with what you said I believe that the method `this.$refs.html2Pdf.generatePdf()` is being called multiple times.

Let's try and debug it, open your inspect element, console tab.
Try adding console.log on your download method and reproduce the preview modal issue and let's see if it logs something on the console

**Comment by kempsteven** [comment]
Feel free to open this if the issue persist!
