### ISSUE TITLE
Can the component act as a wrapper?

### ISSUE THREAD

**Issue by ShetlandJ** [kempsteven/vue-html2pdf#27]
Firstly thank you for providing this repository, which I've found very helpful.

This isn't a bug/code issue but I wasn't sure the best place to ask.

In my Vue file, I have a heap of content:

```
<template>

  // lots of Vue content

</template>
```
I want to use vue-html2pdf and wrap the _existing content_, is that possible? I've tried using it as an outer wrapper for content it does not render/show my Vue code inside the <vue-html2pdf> element.. The only way I've been able to use it so far is like so:

```
<template>
  <div>
    <div>Lots of Vue Content</div>
  
    <vue-html2pdf>
          Lots of Vue content (a copy/paste of the above code, line for line)
    </vue-html2pdf>
  </div>
</template>
```

Is there something I have to do with the props to get it to wrap and display the content inside the wrapper? As it happens, I'm having to copy and paste my code and that's not very D.R.Y.

The `show-layout` props seems to cause the content to float above the page, but I just want to render the Vue code

**Comment by ShetlandJ** [comment]
I solved my own problem using CSS and overrides. If anyone else encounters this issue, I just added this into my css file:

```
<style>
.vue-html2pdf .layout-container {
    position: inherit !important;
    background: inherit !important;
    width: inherit !important;
    overflow: inherit !important;
    height: inherit !important;
}
</style>
```

**Comment by kempsteven** [comment]
Hey, thanks for letting me know, will come up a solution for this use case

**Comment by ShetlandJ** [comment]
Would you accept a PR? I've not contributed to an open source project before but I'd like to try with this one if possible?

**Comment by kempsteven** [comment]
Hmm yeah that would be cool, ill set it up tomorrow

**Comment by ShetlandJ** [comment]
I think I should be able to fork and PR the fork, and that should do it, I'll try tonight. Thanks!

**Comment by kempsteven** [comment]
Sure you could try that, Just make sure you make the current behavior of the layout to be a default and just give them an option of making the layouts content to not float, Thanks as well!

**Comment by ShetlandJ** [comment]
@kempsteven when you're working on it locally, how to do test your changes? I only see build scripts in the package.json (sorry, I've not done much contribution to open source code like this)

**Comment by kempsteven** [comment]
Have not set up any unit tests yet, for now I only do manual testing, you could pull the [vue-html2pdf-demo](https://github.com/kempsteven/vue-html2pdf-demo) to do the test.

I just make sure the changes works on the latest version of Chrome, Mozilla, and Edge.

It's cool man, Its my first time working with someone on an open source project

**Comment by kempsteven** [comment]
Hey man, Just heads up, I might become less busy in the next few days and I might do this update

**Comment by kempsteven** [comment]
This is now done in version 1.7.2, yay

Just need to set `float-layout` to false and you'll be able to do this.

**Comment by ShetlandJ** [comment]
Cool sorry mate I got sidetracked

**Comment by kempsteven** [comment]
Its cool man
