### ISSUE TITLE
Display element only pdf

### ISSUE THREAD

**Issue by enzostvs** [kempsteven/vue-html2pdf#29]
Hi !
I use the module for Nuxt, everything works perfectly, thank you.
I just had a problem, can we add elements in the DOM but **only visible for the pdf generation**?

Thanks,
Enzo

**Comment by kempsteven** [comment]
Hi!
For now, its a bit redundant but to do that use case you could create a separate component for the user facing elements and a separate component for the elements to be converted to a PDF.

May I ask why you need that use case?

**Comment by enzostvs** [comment]
Thank you very much for your feedback.
I need it because on the designer's mock-up the button is integrated at the same level as the pdf elements.

**Comment by kempsteven** [comment]
Ohh okay cool, you're welcome!
