### ISSUE TITLE
TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by enzostvs** [kempsteven/vue-html2pdf#32]
Hi
I local environment i have no error when i generate PDF
So in prod environment i have this error:
<img width="689" alt="Capture d’écran 2020-09-29 à 16 34 38" src="https://user-images.githubusercontent.com/15983122/94572765-ace23d00-0271-11eb-90d7-d69f8038052d.png">

I don't have anywhere in my code a "type" key or any other key...
Thanks you for your help

**Comment by kempsteven** [comment]
Hi, what version are you using?

**Comment by kempsteven** [comment]
I don't have forEach loop on the latest build

**Comment by kempsteven** [comment]
Feel free to open this issue again if it persists, thanks!
