### ISSUE TITLE
Progress always showing 70%

### ISSUE THREAD

**Issue by luiztsmelo** [kempsteven/vue-html2pdf#33]
I am generating a pdf with 13 sections (charts), and it would be great if the progress matched the generated sections, or something like this. It is possible?

**Comment by kempsteven** [comment]
Yeah, for now the progress is only for pagination and pdf generation. thats why its only 70% then 100%.

This package relies on html2pdf.js.
In their documentation they mentioned that they have a [progress tracking](https://www.npmjs.com/package/html2pdf.js#progress-tracking), but its not very clear how we get that progress, that is the reason why we dont have a proper progress yet, would still have to investigate how to get the progress.

If you want to have full access to html2pdf.js API and investigate how to get the progress tracking, you could use the @beforeDownload event, details are [here](https://www.npmjs.com/package/vue-html2pdf#sample-use-case-of-beforedownload)

**Comment by luiztsmelo** [comment]
Ok, thanks @kempsteven
