### ISSUE TITLE
Property 'generatePdf' does not exist on type 'Vue'.

### ISSUE THREAD

**Issue by jeffersonbabuyo** [kempsteven/vue-html2pdf#36]
I am getting this error when using it on vuejs with typescript.

I have imported it and register it in my @Component()

![image](https://user-images.githubusercontent.com/10564871/96416091-21c9e680-1222-11eb-8140-5d9e22944c97.png)

**Comment by jeffersonbabuyo** [comment]
all good now....closing this issue

**Comment by sebin-simon** [comment]
Could you please share the working demo? where  I need to add any?

**Comment by kempsteven** [comment]
@s4sebin 

here you go:
**Demo Site:**
https://vue-html2pdf-demo.netlify.com/

**Demo Github repo:**
https://github.com/kempsteven/vue-html2pdf-demo

**Comment by lartheon** [comment]
> all good now, simply add `$refs!: any` ....closing this issue

I'm experiencing this issue, can you please explain where do you add this? Also I'm using typescript so I can't use 'any', what is the proper type to replace it with?

**Comment by Master-Y0da** [comment]
Same error here ... @jeffersonbabuyo  could you please share the complete instruction ?

**Comment by kempsteven** [comment]
Hey guys can you try this?
if this is a typescript error, i think this could be the fix

```
const html2pdfComponent: any = this.$refs.html2pdf 
html2pdfComponent.generatePdf()
```

or have a look at this, this is where $refs type are inserted.
https://class-component.vuejs.org/guide/refs-type-extension.html
![image](https://user-images.githubusercontent.com/51051704/112399885-11beb180-8d42-11eb-9994-5b9d1c0dcad0.png)
