### ISSUE TITLE
spacing on top after pdf is generated

### ISSUE THREAD

**Issue by jeffersonbabuyo** [kempsteven/vue-html2pdf#37]
hello @kempsteven , I am trying to use this package to generate pdf but I am curios why there's a few spacing on heading part? 
![image](https://user-images.githubusercontent.com/10564871/96487881-cd4d5800-126f-11eb-9fd6-38e31fde990d.png)

here is on how I did use it: 
![image](https://user-images.githubusercontent.com/10564871/96487943-e1915500-126f-11eb-8d4b-c4b72190ac90.png)

**Comment by kempsteven** [comment]
Hi @jeffersonbabuyo,
hmmm possibly a styling issue, can you add `border: 1px solid red;` on all elements of pdf-content?

**Comment by jeffersonbabuyo** [comment]
Hi @kempsteven - you mean like this? 
![image](https://user-images.githubusercontent.com/10564871/96538521-49c15480-12cb-11eb-9847-ad49c35e62e8.png)

**Comment by jeffersonbabuyo** [comment]
I also tried like this:

![image](https://user-images.githubusercontent.com/10564871/96538840-1c28db00-12cc-11eb-82e2-8b82ae99a899.png)

Then after generating

![image](https://user-images.githubusercontent.com/10564871/96538860-2a76f700-12cc-11eb-8b55-0603cf3c9c0b.png)

**Comment by kempsteven** [comment]
hmmm cant seem to replicate it on my side, what version are you using?
also can I get a sample of your `pdf-content` so I can debug it on my side?

**Comment by kempsteven** [comment]
**Result of replication:**
version: 1.8.0

![image](https://user-images.githubusercontent.com/51051704/96575175-01258d80-1303-11eb-9721-adceb0fe67ef.png)

**Sample of my `pdf-content`:**

![image](https://user-images.githubusercontent.com/51051704/96575254-1c909880-1303-11eb-8ae4-40da223d280a.png)

PS No need to inline style was just lazy lol

**Comment by jeffersonbabuyo** [comment]
Hello @kempsteven - I agree on you it's a css issue. It is now fixed and closing this ticket.

**Comment by kempsteven** [comment]
Cool, can you share what css issue was it so that I could that note of it?

**Comment by jeffersonbabuyo** [comment]
Hello @kempsteven - It wasn't the package css issue that is causing the problem it was my custom css that I implemented.
