### ISSUE TITLE
Units passed to jsPDF, seems to have no effect

### ISSUE THREAD

**Issue by Neophen** [kempsteven/vue-html2pdf#40]
**Describe the bug**
When using the `html-to-pdf-options` prop, the `jsPDF` units options seems to have no and always assumes `pt`. 

**To Reproduce**
```js
    const htmlToPdfOptions = {
      jsPDF: {
        unit: "mm", //this seems to not do anything
        format: [86, 54], // this is passed, but assumes units in `pt`
        orientation: "landscape",
      },
    };
```

**Package Version**
1.8.0

**Comment by Neophen** [comment]
After looking at the source it seems this is an issue with jsPdf, and not this library as you're simply passing the config.

**Comment by kempsteven** [comment]
Alright cool, I'll be closing this now.
