### ISSUE TITLE
text based pdf

### ISSUE THREAD

**Issue by Redhaus** [kempsteven/vue-html2pdf#47]
Hello sir, 

Quick question on your library 
Does this pdf generator have the ability to keep the text as text or does it turn everything into an image. 
I have mostly text-based content I need to generate PDF's from, but I need the PDF's to be searchable after download

Any insight you can offer would be much appreciated.

**Comment by kempsteven** [comment]
Hey @Redhaus,
Unfortunately html2pdf.js renders all content into an image, then places that image into a PDF.
keeping the text as text is not possible yet.

**Comment by Redhaus** [comment]
No worries, I totally understand. Not your fault. 
On another note, if you need this functionality in any of your projects. Where text stays text. 
I found this project that allows HTML to be converted directly to pdf using WebKit print functionality. 
It looks promising, but I have to dig into it deeper. I hope it helps. 

https://github.com/vivliostyle/vivliostyle-print

**Comment by kempsteven** [comment]
Okay cool thanks for letting me know,
I'll be closing this issue, feel free to open another one if you have any issue
