### ISSUE TITLE
How should we use it when we are going to print the paper based on a set of HTML structures

### ISSUE THREAD

**Issue by qklhk** [kempsteven/vue-html2pdf#48]
**hello vue-html2pdf author**

I'm in the application vue-html2pdf plug-in We need to present our exam papers in terms of a set of HTML structures，
How do you move a question that is in the middle of two pages to the next page，
Print our test paper and PDF to make it look better

`      <vue-html2pdf
        :show-layout="false"
        :float-layout="true"
        :enable-download="true"
        :preview-modal="true"
        :paginate-elements-by-height="1400"
        filename="hee hee"
        :pdf-quality="2"
        :manual-pagination="false"
        pdf-format="a4"
        pdf-orientation="landscape"
        pdf-content-width="1140px"
        ref="html2Pdf"
      >
        <paper-show  slot="pdf-content"/>
      </vue-html2pdf>`

![1111](https://user-images.githubusercontent.com/52808354/100404809-432db600-309d-11eb-81c0-f3037cd64c02.png)

Situation as above

From a VUE developer in China

**Comment by kempsteven** [comment]
Hello,

Have you tried reducing the props `:paginate-elements-by-height` value? That's the value that determines when to page break every page.

Also read this guide on the documentation, you need to format your HTML in a specific way for page breaks to perfectly work:
https://github.com/kempsteven/vue-html2pdf#guide

If things still didn't work out, please comment here again, thanks!

**Comment by qklhk** [comment]
And in our application the height is variable, so how do we solve that?

**Comment by qklhk** [comment]
My requirement is that when the current topic is split in pages, we move the current topic (including the next topic) to the next page

**Comment by kempsteven** [comment]
Okay so you want your topic to stay together when pagination happens right?
You should contain them in one parent element.

**For example this is your `pdf-content` elements:**
```html
<div slot="pdf-content">
  <div class="parent-element">
      <div class="question">
          4. illustrator lorem ipsum dorem bla bla illustrator lorem ipsum dorem bla bla 
          illustrator lorem ipsum dorem bla bla illustrator lorem ipsum dorem bla bla 
       </div>

        <div class="answers">A. Tab</div>
        <div class="answers">B. Lorem Ipsum</div>
        <div class="answers">C. Shift</div>
  </div>
</div>
```

as you can see they are inside a parent element, those elements inside will be paginated together.
also please try playing with the props `:paginate-elements-by-height`, and see what value fit your needs.

**Comment by qklhk** [comment]
I am very sorry that my problem has been solved and I just saw your information

**Comment by kempsteven** [comment]
No prob :)
