### ISSUE TITLE
Weird space at starting of PDF

### ISSUE THREAD

**Issue by SeedSuite** [kempsteven/vue-html2pdf#52]
When Generate pdf after scrolling some part of visible content of data, PDF get  unexpected weird space on top.
But when generating PDF without scrolling, It works great.

[hee hee (2).pdf](https://github.com/kempsteven/vue-html2pdf/files/5758827/hee.hee.2.pdf)

"vue-html2pdf": "^1.8.0",
"vue": "^2.6.10",

Here I am uploaded generated PDF from your given demo. When I scroll some content of data and generate the PDF, it got some space on top of Pdf (Refer the attached PDF). But when generate the Pdf without scrolling, It works great.

**Comment by cesolutions** [comment]
Did you end up what was causing this issue? I am experiencing a similar issue
