### ISSUE TITLE
 undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git

### ISSUE THREAD

**Issue by shane-henderson** [kempsteven/vue-html2pdf#58]
Hi

Although I don't think this is a direct issue with vue-html2pdf, unfortunately at the moment I can't install via npm as I'm getting the above error.  vue-html2pdf looks awesome, I'd love to be able to install it and use it in my application.  I am simply trying to run: `npm i vue-html2pdf `.  
[2021-01-31T07_16_15_734Z-debug.log](https://github.com/kempsteven/vue-html2pdf/files/5899331/2021-01-31T07_16_15_734Z-debug.log)

**Comment by kempsteven** [comment]
Can you try this solution?

Install jspdf 1.5.2: npm i jspdf@1.5.2
install this plugin: npm i vue-html2pdf

**Comment by shane-henderson** [comment]
Thank you Steven! That worked !

**Comment by kempsteven** [comment]
Cool, You're welcome!
