### ISSUE TITLE
utf8 (Persian, Arabic, ... ) support.

### ISSUE THREAD

**Issue by farshidrezaei** [kempsteven/vue-html2pdf#59]
how i can use this package for utf texts?

original:
![Result](https://i.ibb.co/rM6L1tq/Screenshot-from-2021-02-02-09-26-26.png)

exported:
![Result](https://i.ibb.co/XLCPT6f/Screenshot-from-2021-02-02-09-23-00.png)

**Comment by kempsteven** [comment]
I haven't tested yet, could you try this one?
https://stackoverflow.com/a/30557501/10020611

```
This is a bug with html2canvas (Arabic Encoding with html2canvas) and can be
fixed by setting text-align: left on your wrapper element.

Here's an updated fiddle http://jsfiddle.net/ydeL72m8/1/
```

**Comment by farshidrezaei** [comment]
> I haven't tested yet, could you try this one?
> https://stackoverflow.com/a/30557501/10020611
> 
> ```
> This is a bug with html2canvas (Arabic Encoding with html2canvas) and can be
> fixed by setting text-align: left on your wrapper element.
> 
> Here's an updated fiddle http://jsfiddle.net/ydeL72m8/1/
> ```

thanks . `text-align` must be `left` or `right`. if be `center` result will be incorrect.
