### ISSUE TITLE
Content is not splitted in pages.

### ISSUE THREAD

**Issue by DespertaWeb** [kempsteven/vue-html2pdf#6]
Hi, I just found out that content is not being splitted. Also I've got a initial blank page.
Is there any way to solve this issues? **I'm desperate!**
I've got '#terms-and-conditions' where the content is.
Then I'll clone and append to :
```
    <vue-html2pdf
      ref="html2Pdf"
      :show-layout="false"
      :enable-download="false"
      :preview-modal="true"
      :paginate-elements-by-height="1400"
      filename="hee hee"
      :pdf-quality="0.8"
      pdf-format="a4"
      pdf-orientation="portrait"
      pdf-content-width="800px"
    >
      <div ref="pdfContainer" class="row" slot="pdf-content" />
    </vue-html2pdf>
```

```
 generatePdf() {
      const content = document.querySelector('#terms-and-conditions')

      this.$refs.pdfContainer.append(content)
      this.$refs.html2Pdf.generatePdf()

    },
```

No break page:
![imatge](https://user-images.githubusercontent.com/13997454/82905683-75325400-9f64-11ea-9e82-a2d2a5d220f7.png)

Initial blank page: 
![imatge](https://user-images.githubusercontent.com/13997454/82914605-00fdad80-9f70-11ea-9e21-e742a6bf2808.png)

**Comment by kempsteven** [comment]
Hey there,

For the No Break page:
You can control the break on pages by adjusting the prop `:paginate-elements-by-height`, maybe try setting it to a lower value.

For the Initial blank page:
Can I get a sample of the section of #terms-and-conditions

also if you have not seen the on the docu, this could be an issue with how you structured your html
your html should be like on the guide section
https://github.com/kempsteven/vue-html2pdf#guide

**Comment by DespertaWeb** [comment]
> the <section class="pdf-item"> will get split apart but, the children elements of <section class="pdf-item"> will not be split apart on process of pagination

That might be the case. Anyway, I'm already about to get it done with html2pdf.js . Thank you so much!
