### ISSUE TITLE
Vue 3 support?

### ISSUE THREAD

**Issue by Sun3** [kempsteven/vue-html2pdf#64]
I installed vue-html2pdf with ```npm i vue-html2pdf``` with a Vue 3 and Typescript application but it does not seem to be compatible. When I try to import ```import VueHtml2pdf from 'vue-html2pdf'``` you get an error ```Could not find a declaration file for module 'vue-html2pdf'```

I also tried ```npm i --save-dev @types/vue-html2pdf``` but that did not work, lot's of errors.

Any suggestions?
Thank you.

**Comment by kempsteven** [comment]
Hello @Sun3, unfortunately Vue 3 support for this project is not yet available

**Comment by Sun3** [comment]
ok, thanks...

**Comment by kempsteven** [comment]
Maybe in the future, but there is no exact date yet, anyways thanks for trying the package!

**Comment by dmitryT93** [comment]
try to use change import VueHtml2pdf from 'vue-html2pdf' 
to const VueHtml2pdf = require('vue-html2pdf')

**Comment by Shujee** [comment]
3 years since this question was asked. Has anything changed since then? Do we have Typescript support yet or on the cards? Is there an alternate available?
