### ISSUE TITLE
Doesn't handle vuetify styles

### ISSUE THREAD

**Issue by dudif91** [kempsteven/vue-html2pdf#67]
seems like the package ignored the styles of vuetify components.

vue component (vuetify)
![Screen Shot 2021-03-03 at 11 56 52](https://user-images.githubusercontent.com/57500905/109788296-d6840380-7c17-11eb-8f59-ccf84672d298.png)

pdf previewer
![Screen Shot 2021-03-03 at 11 56 43](https://user-images.githubusercontent.com/57500905/109788266-ccfa9b80-7c17-11eb-8cc4-8837481bded3.png)

**Package Version**
1.8.0

**Additional context**
nice package but I really need it to show styles hope to get some help

**Comment by Yelloz** [comment]
If you try to add 
```
<v-app>
  <v-main>
    <v-container>
```
inside `<section slot="pdf-content">`

```
<vue-html2pdf
    ...params
>
    <section slot="pdf-content">
      <v-app>
        <v-main>
          <v-container>
            Your content
          </v-container>
        </v-main>
      </v-app>
    </section>
</vue-html2pdf>
```

Does it work for you?
Don't know if it's the proper way to do this but it works on my side.

**Comment by dudif91** [comment]
don't know why but it works.... thanks!

**Comment by dudif91** [comment]
don't know why but it works...thanks!

actually 

> ```
> 
> inside `<section slot="pdf-content">`
> 
> ```
> <vue-html2pdf
>     ...params
> >
>     <section slot="pdf-content">
>       <v-app>
>             Your content
>       </v-app>
>     </section>
> </vue-html2pdf>
> ```
> 
also worked

**Comment by kempsteven** [comment]
I'll take note of this.

it probably has to do with the vuetify css library.
the library looks something like this:
![image](https://user-images.githubusercontent.com/51051704/109908152-b5d2b100-7cde-11eb-9521-21aa7073d3b2.png)

I think all css classes is inside the .v-application, i believe html2pdf.js generates the pdf on a separate html doc, and so without the v-app tag, all pdf contents won't be able to use the vuetify css library. thats just a theory tho, and I haven't exactly investigated it fully.

**Comment by dudif91** [comment]
@kempsteven I think you're right. I've tested your theory by just using a simple div with "v-application" class name and it worked
