### ISSUE TITLE
Add page number of total pages at beforeDownload

### ISSUE THREAD

**Issue by rzpjunior** [kempsteven/vue-html2pdf#72]
is there any documentation on how to add page number of total pages?

i have tried this : 
```
async beforeDownload ({ html2pdf, options, pdfContent }) {
      await html2pdf().set(options).from(pdfContent).toPdf().get('pdf').then((pdf) => {
				const totalPages = pdf.internal.getNumberOfPages()
				for (let i = 1; i <= totalPages; i++) {
					pdf.setPage(i)
					pdf.setFontSize(10)
					pdf.setTextColor(150)
					pdf.text('Page ' + i + ' of ' + totalPages, (pdf.internal.pageSize.getWidth() * 0.88), (pdf.internal.pageSize.getHeight() - 0.3))
				} 
      }).save()
    }
```
but it doesnt seem to be working

**Comment by kempsteven** [comment]
Hey, try pulling this demo app
https://github.com/kempsteven/vue-html2pdf-demo

go to App.vue
set the props  `enable-download:`,  `preview-modal:` to false

and search for the `beforeDownload` function
and uncomment that then generate a pdf, it will work.
