### ISSUE TITLE
How to open new tab when generating pdf

### ISSUE THREAD

**Issue by rzpjunior** [kempsteven/vue-html2pdf#73]
Hello,

Is there any documentation on how to open new browser tab to preview the PDF when i click generate PDF button?

**Comment by bad-mushroom** [comment]
Not sure about opening a new tab but there is an option to open a preview modal:
```
<vue-html2pdf
     :preview-modal="true"
>
```

**Comment by rzpjunior** [comment]
[SOLVED]
I just did this to beforeDownload function : 

`
window.open(pdf.output('bloburl'), '_blank');
`
