### ISSUE TITLE
Feature Request: Support persian language

### ISSUE THREAD

**Issue by hasanparasteh** [kempsteven/vue-html2pdf#79]
Hi. Thanks for your great work. Please consider supporting RTL languages like `Persian`. when I want to generate PDF the text is messed up like the image below:

<img width="1280" alt="Screen Shot 2021-05-01 at 5 38 06 PM" src="https://user-images.githubusercontent.com/42239446/116783438-4844c600-aa7e-11eb-99f3-5195e162521d.png">

Please help me to fix this problem.

**Comment by hasanparasteh** [comment]
`text-align` trick wont work now!

**Comment by kempsteven** [comment]
Hey man, so this package is a wrapper and uses `html2pdf.js`, and `html2pdf.js` uses these packages `html2canvas` & `jsPDF`,
Unfortunately I don't have any fixes on my end.

You can have a look at html2canvas's repo issues around unicode & arabic/persian font:
https://github.com/niklasvh/html2canvas/labels/Unicode
