### ISSUE TITLE
Doesn't support <style> tag

### ISSUE THREAD

**Issue by bArraxas** [kempsteven/vue-html2pdf#8]
Hi,

It seems the library doesn't support <style> tag.
How can I customize the style for print for exemple (I mean without use style attribute) ?

Thanks for your help

**Comment by bArraxas** [comment]
I said a mistake. It's vuejs who doesn't not support the "<style>".
To solve that in vuejs use that into the template : 
`<div is="style" type="text/css">`

**Comment by kempsteven** [comment]
Haha yep you can just use the  `<style>` tag beneath the `<template>` to style your elements

**Sample:**

```
<template>
   ...
</template

<style lang="scss" scoped>
.pdf-item {
    background: #555;
}
</style>
```
