### ISSUE TITLE
How to automatically print the pdf instead of downloading?

### ISSUE THREAD

**Issue by t8ysn** [kempsteven/vue-html2pdf#81]
Is there a way o get the pdf process to autimatically open and do a 'windows.print()'?

**Comment by kempsteven** [comment]
set the props: `enable-download` and `preview-modal` to false,
use the @beforeDownload event, you can get the pdf blob in that event,
using the pdf blob, you can do something like this?
https://codepen.io/Edo_M/pen/PjdKEd?editors=1010

here is the docs for @beforeDownload:
https://github.com/kempsteven/vue-html2pdf#sample-use-case-of-beforedownload

**Comment by abdelhak51** [comment]
you can use this code to solve it using vue-html2pdf beforeDomnload   function and adding the line (window.open(pdf.output('bloburl'), '_blank')  will open it in new tab 

```
async beforeDownload ({ html2pdf, options, pdfContent }) {
            await html2pdf().set(options).from(pdfContent).toPdf().get('pdf').then((pdf) => {
                const totalPages = pdf.internal.getNumberOfPages()
                for (let i = 1; i <= totalPages; i++) {
                    pdf.setPage(i)
                    pdf.setFontSize(10)
                    pdf.setTextColor(150)
                    pdf.text('Page ' + i + ' of ' + totalPages, (pdf.internal.pageSize.getWidth() * 0.88), (pdf.internal.pageSize.getHeight() - 0.3))
                }
                   // this line will open the pdf in new tab 
                    window.open(pdf.output('bloburl'), '_blank')
            }).save()

            },
```

**Comment by abdelhak51** [comment]
> set the props: `enable-download` and `preview-modal` to false,
> use the @beforeDownload event, you can get the pdf blob in that event,
> using the pdf blob, you can do something like this?
> https://codepen.io/Edo_M/pen/PjdKEd?editors=1010
> 
> here is the docs for @beforeDownload:
> https://github.com/kempsteven/vue-html2pdf#sample-use-case-of-beforedownload

but when setting to preview-modal  and  enable-download  to false it still downloading

**Comment by layang1208** [comment]
Hi @abdelhak51

Is this works on mobile? It works on chrome desktop version, but not on any mobile browser
