### ISSUE TITLE
Attribute "paginate-elements-by-height" generate a bug

### ISSUE THREAD

**Issue by bArraxas** [kempsteven/vue-html2pdf#9]
Hi,

Attribute "paginate-elements-by-height" generate a bug if it too small.
In this case, the browser freeze and the processus use 99% of processor.

I think it's a bug not catched. You could genrate a warning in the console.

Thanks for you work ;)

**Comment by kempsteven** [comment]
Hey, thanks for raising that, I will be looking into that

**Comment by bArraxas** [comment]
Great job !
The previous version (1.3) was buged, i had all tryed but sometimes the script run at infinite (100% processor activity) without render any pdf :(
This version (1.6) never bug what i seen !

It's just in console you (or html2pdf) forgot to disabled the "trace mode" ;-)
