### ISSUE TITLE
Print on paper roll

### ISSUE THREAD

**Issue by 72fcosta** [kempsteven/vue-html2pdf#98]
Hello.
Is it possible to print on paper roll (without breaking the page before the end of the content)?
Width = 80mm
Height = depends of the content (> 10000mm)
Thanks.

![image](https://user-images.githubusercontent.com/25357754/128517695-550cce43-dfac-4f89-8a2d-c2209ba44133.png)

**Comment by kempsteven** [comment]
You can disable pagination by setting :manual-pagination="true"
